#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include <cstring>
#include <sstream>
#include <cmath>
#include <string>
#include <iomanip>
#include <algorithm>
#include <stdio.h>
#include <stdlib.h>
#include <openssl/rand.h>
